---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  /health_checks:
    $ref: "./paths/health_checks.yml"

# components:
#   securitySchemes:
#     Bearer:
#       description: Bearer token
#       type: apiKey
#       name: Authorization
#       in: header

# security:
#   - Bearer: []

servers:
  - url: http://0.0.0.0:3000/api/v1
